### ISSUE TITLE
pip error: no such option: --use-deprecated

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneconf.org#32]
on M1 macOS Monterey 12.2.1:

```
% make install
Install API & Frontend
==> Setup Virtual Env
Collecting pip==19.3.1
  Downloading pip-19.3.1-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 4.0 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-19.3.1
Collecting setuptools==57.4.0
  Downloading https://files.pythonhosted.org/packages/bd/25/5bdf7f1adeebd4e3fa76b2e2f045ae53ee208e40a4231ad0f0c3007e4353/setuptools-57.4.0-py3-none-any.whl (819kB)
     |████████████████████████████████| 819kB 3.6MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed setuptools-57.4.0
WARNING: You are using pip version 19.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
==> Install Plone and create instance

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --use-deprecated
make[2]: *** [bin/mkwsgiinstance] Error 2
make[1]: *** [build-api] Error 2
make: *** [install] Error 2
```

**Comment by tkimnguyen** [comment]
according to https://github.com/exasol/script-languages-release/issues/150 `--use-deprecated=legacy-resolver only will work until pip 21.0, so we need to have a look at what the resolver does differently to the legacy resolver`

**Comment by tkimnguyen** [comment]
```
% cd api
% vi Makefile
% bin/pip --version
pip 19.3.1 from /Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by tkimnguyen** [comment]
```
% bin/pip install --use-deprecated=legacy-resolver -r requirements/plone.txt

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --use-deprecated
% bin/pip install -r requirements/plone.txt
Ignoring Products.ATContentTypes: markers 'python_version < "3.0"' don't match your environment
Ignoring Products.Archetypes: markers 'python_version < "3.0"' don't match your environment
Ignoring Products.Marshall: markers 'python_version < "3.0"' don't match your environment
Ignoring Products.TinyMCE: markers 'python_version < "3.0"' don't match your environment
Ignoring PyGithub: markers 'python_version < "3.0"' don't match your environment
Ignoring SecretStorage: markers 'python_version < "3.0"' don't match your environment
Ignoring archetypes.multilingual: markers 'python_version < "3.0"' don't match your environment
Ignoring archetypes.referencebrowserwidget: markers 'python_version < "3.0"' don't match your environment
Ignoring archetypes.schemaextender: markers 'python_version < "3.0"' don't match your environment
Ignoring check-manifest: markers 'python_version < "3.0"' don't match your environment
Ignoring docutils: markers 'python_version < "3.0"' don't match your environment
Ignoring feedparser: markers 'python_version < "3.0"' don't match your environment
Ignoring functools32: markers 'python_version < "3.0"' don't match your environment
Ignoring futures: markers 'python_version < "3.0"' don't match your environment
Ignoring keyring: markers 'python_version < "3.0"' don't match your environment
Ignoring markdown: markers 'python_version < "3.0"' don't match your environment
Ignoring pip: markers 'python_version < "3.0"' don't match your environment
Ignoring plone.app.blob: markers 'python_version < "3.0"' don't match your environment
Ignoring plone.app.collection: markers 'python_version < "3.0"' don't match your environment
Ignoring plone.app.controlpanel: markers 'python_version < "3.0"' don't match your environment
Ignoring plone.app.imaging: markers 'python_version < "3.0"' don't match your environment
Ignoring plone.app.referenceablebehavior: markers 'python_version < "3.0"' don't match your environment
Ignoring sourcecodegen: markers 'python_version < "3.0"' don't match your environment
Ignoring sphinxcontrib-websupport: markers 'python_version < "3.0"' don't match your environment
Ignoring trollius: markers 'python_version < "3.0"' don't match your environment
Ignoring twine: markers 'python_version < "3.0"' don't match your environment
Ignoring typing: markers 'python_version < "3.0"' don't match your environment
Ignoring watchdog: markers 'python_version < "3.0"' don't match your environment
Collecting Paste==3.5.0
  Downloading https://files.pythonhosted.org/packages/7a/b0/ca8825989b9c6203f36f80fef31be5144df3ff3461efec3f34615b6a7f99/Paste-3.5.0-py2.py3-none-any.whl (593kB)
     |████████████████████████████████| 593kB 3.9MB/s
Collecting Plone==5.2.5
  Downloading https://files.pythonhosted.org/packages/6b/bb/58c2c7754353dae7e6a844624758a5b73800b7505e5213e9434ac76a6c3c/Plone-5.2.5-py2.py3-none-any.whl
Collecting Products.CMFPlacefulWorkflow==2.0.4
  Downloading https://files.pythonhosted.org/packages/fe/7b/09e5dc61fe847b760cbd9d0d7871b00f1fb684b3045b5c4ad1e7bb2ca3bd/Products.CMFPlacefulWorkflow-2.0.4-py2.py3-none-any.whl (64kB)
     |████████████████████████████████| 71kB 13.0MB/s
Collecting Products.CMFPlone==5.2.5
  Downloading https://files.pythonhosted.org/packages/a8/b1/7f746d0ecf0fc95c3e81585aa4f6dddca04be643509aa803754d736ab7e6/Products.CMFPlone-5.2.5-py2.py3-none-any.whl (792kB)
     |████████████████████████████████| 798kB 18.3MB/s
Collecting Products.CMFQuickInstallerTool==4.0.4
  Downloading https://files.pythonhosted.org/packages/ab/1e/8b148424a2a6cd61fe6b5b7093f70458b427277d6103295789671ef98edd/Products.CMFQuickInstallerTool-4.0.4-py2.py3-none-any.whl (45kB)
     |████████████████████████████████| 51kB 13.1MB/s
Collecting Products.CMFUid==3.1.0
  Downloading https://files.pythonhosted.org/packages/83/62/89fddcc5c1fe297ed4a6ff7d5475135edee0c1a83f1f8658218e80a8f543/Products.CMFUid-3.1.0-py2.py3-none-any.whl
Collecting Products.DCWorkflow==2.5.0
  Downloading https://files.pythonhosted.org/packages/4f/cf/6396068dd7fd0d693ad52c3c9c8ad09635fedf28086be7b6a9dfe1d2291c/Products.DCWorkflow-2.5.0-py2.py3-none-any.whl (83kB)
     |████████████████████████████████| 92kB 18.7MB/s
Collecting Products.ExtendedPathIndex==4.0.1
  Downloading https://files.pythonhosted.org/packages/c9/b8/d2a05d27a9a36e2202005a6323670ee0166f60670aaeefd9cfcb65dcd84e/Products.ExtendedPathIndex-4.0.1-py2.py3-none-any.whl
Collecting Products.ExternalMethod==4.5
  Downloading https://files.pythonhosted.org/packages/6b/0c/ee7f7cba789487a7b01d82ce2627b3900392688771847fe83d0ad055ce4f/Products.ExternalMethod-4.5-py2.py3-none-any.whl
Collecting Products.GenericSetup==2.1.3
  Downloading https://files.pythonhosted.org/packages/81/87/1bf572e358bd478c987db55e5e26dff835c62430ceb0169b529e5e810248/Products.GenericSetup-2.1.3-py2.py3-none-any.whl (175kB)
     |████████████████████████████████| 184kB 18.7MB/s
Collecting Products.MimetypesRegistry==2.1.8
  Downloading https://files.pythonhosted.org/packages/6e/ef/7c99a19bf63d49b4e50d1455c0ec90188db51b135a4b6bafc98e4ae1e406/Products.MimetypesRegistry-2.1.8-py2.py3-none-any.whl (436kB)
     |████████████████████████████████| 440kB 19.4MB/s
Collecting Products.PlonePAS==6.0.8
  Downloading https://files.pythonhosted.org/packages/90/5e/8045702e0f27df822f4d41efd59be05aa2a05963618883b209da3c2b8f73/Products.PlonePAS-6.0.8-py2.py3-none-any.whl (118kB)
     |████████████████████████████████| 122kB 17.9MB/s
Collecting Products.PluggableAuthService==2.6.4
  Downloading https://files.pythonhosted.org/packages/c7/83/ec8bc37eb714f7b18422bc106bdd1fe581f62f08fdd61a592d9104b1a694/Products.PluggableAuthService-2.6.4-py2.py3-none-any.whl (218kB)
     |████████████████████████████████| 225kB 18.7MB/s
Collecting Products.PluginRegistry==1.9
  Downloading https://files.pythonhosted.org/packages/77/0a/24f9fb37320310ebfb0d8603b7b875dc792a47c9980631632dac0ff7303c/Products.PluginRegistry-1.9-py2.py3-none-any.whl
Collecting Products.PortalTransforms==3.1.11
  Downloading https://files.pythonhosted.org/packages/07/81/4d4b2e5aba979f2e6522a32b49bcd868e5fda193495e227921f8ce525632/Products.PortalTransforms-3.1.11-py2.py3-none-any.whl (234kB)
     |████████████████████████████████| 235kB 17.0MB/s
Collecting Products.PythonScripts==4.13
  Downloading https://files.pythonhosted.org/packages/52/40/f5deb134972498ee3bf9e08cfbc62ec2c01f488ca7747df1b1ffb9b8998d/Products.PythonScripts-4.13-py2.py3-none-any.whl
Collecting Products.Sessions==4.9
  Downloading https://files.pythonhosted.org/packages/c4/d1/29d5c63740bae0a272b9d57ff867e38cdf2f3314adc46ddcc51b0d31cb03/Products.Sessions-4.9-py2.py3-none-any.whl (70kB)
     |████████████████████████████████| 71kB 18.0MB/s
Collecting Products.SiteErrorLog==5.5
  Downloading https://files.pythonhosted.org/packages/55/72/50af560cb0e8bdf558237661b3ced76828be31326ab53a5e6b671afb7f04/Products.SiteErrorLog-5.5-py2.py3-none-any.whl
Collecting Products.StandardCacheManagers==4.0.3
  Downloading https://files.pythonhosted.org/packages/8a/f3/da1c226849940cf302710723b231b5c5cae854c14be6e9a116fa6b89dbe9/Products.StandardCacheManagers-4.0.3-py2.py3-none-any.whl
Collecting Products.TemporaryFolder==5.3
  Downloading https://files.pythonhosted.org/packages/a9/fc/0148484c8d93677dbd8f70cb4ad615c3ba7302978e8ee7d8cbcf17c4e3e8/Products.TemporaryFolder-5.3-py2.py3-none-any.whl
Collecting Products.ZCatalog==5.2
  Downloading https://files.pythonhosted.org/packages/3e/43/958623a149924ef929843ebbc4312a006f1ebb5c2beb69cdef6c2528ddf8/Products.ZCatalog-5.2-py2.py3-none-any.whl (230kB)
     |████████████████████████████████| 235kB 19.3MB/s
Collecting Products.isurlinportal==1.2.0
  Downloading https://files.pythonhosted.org/packages/78/ca/f18d3918a286c8bde8f60f6f5174de6241a03d88eebb783a5475ad51b872/Products.isurlinportal-1.2.0-py2.py3-none-any.whl
Collecting Products.statusmessages==5.0.5
  Downloading https://files.pythonhosted.org/packages/0c/27/b11bfb05f15640bf1bb2a35ae96d6b822bcc7bc1fe1388950508b53cc01a/Products.statusmessages-5.0.5-py2.py3-none-any.whl
Collecting Record==3.5
  Downloading https://files.pythonhosted.org/packages/84/51/7194e34137303e44cfc31874b3386ea47c2193cf81f9d1bfa27a7f503700/Record-3.5-py2.py3-none-any.whl
Collecting RestrictedPython==5.1
  Downloading https://files.pythonhosted.org/packages/a0/cc/28c4d966615a46b03be4dac0f2c6e713412efbf2f85428eeb9618c4f6f0c/RestrictedPython-5.1-py2.py3-none-any.whl
Collecting ZODB==5.6.0
  Downloading https://files.pythonhosted.org/packages/0a/f4/5398a4f42df540fd5d3b24dec3de30d54ee2775f3f26f6d6cb2fe5c27c37/ZODB-5.6.0-py2.py3-none-any.whl (413kB)
     |████████████████████████████████| 419kB 16.5MB/s
Collecting ZODB3==3.11.0
  Downloading https://files.pythonhosted.org/packages/ae/0a/27521b4102a47c205f3a40d1bb117365bc3f5e6df0267413404e159469c4/ZODB3-3.11.0.tar.gz (55kB)
     |████████████████████████████████| 61kB 10.2MB/s
Collecting Zope==4.6.3
  Downloading https://files.pythonhosted.org/packages/7d/33/a60860760dea34144d076ef0aca3bbe6f5a836b8c9063caaf1df4a53daaa/Zope-4.6.3-py2.py3-none-any.whl (3.1MB)
     |████████████████████████████████| 3.1MB 9.4MB/s
Collecting Zope2==4.0
  Downloading https://files.pythonhosted.org/packages/0c/b6/b05c357f7855b80847a2ac0de47352823ef6534e71d2c532686a973531bd/Zope2-4.0.tar.gz
Collecting borg.localrole==3.1.8
  Downloading https://files.pythonhosted.org/packages/a1/ff/1855a37d0e88e18b8abe58d240a0ce2aac0ef600a9e41430b4bbbeb8ba64/borg.localrole-3.1.8-py2.py3-none-any.whl
Collecting calmjs.parse==1.2.5
  Downloading https://files.pythonhosted.org/packages/15/9d/63d6125d7b238f9d234edc025985d8a3cec66bfeda754186e702ad5e8641/calmjs.parse-1.2.5-py3-none-any.whl (272kB)
     |████████████████████████████████| 276kB 16.8MB/s
Collecting five.customerize==2.0.1
  Downloading https://files.pythonhosted.org/packages/d2/b2/e513fe976241fd85e5c9ef049a3f8ef2975a5ba4b56a05dc5e9d0cc7df66/five.customerize-2.0.1-py2.py3-none-any.whl
Collecting five.localsitemanager==3.2.2
  Downloading https://files.pythonhosted.org/packages/34/9b/f128d7e6f3f627e3725bc5d16aa3115e1bbdccb7f5bab39a31ab59d85523/five.localsitemanager-3.2.2-py2.py3-none-any.whl
Collecting markdown==3.2.2
  Downloading https://files.pythonhosted.org/packages/a4/63/eaec2bd025ab48c754b55e8819af0f6a69e2b1e187611dd40cbbe101ee7f/Markdown-3.2.2-py3-none-any.whl (88kB)
     |████████████████████████████████| 92kB 17.6MB/s
Collecting mockup==3.2.6
  Downloading https://files.pythonhosted.org/packages/ff/a4/5a3444c35f2af47b33089b479bd16e4af67fd3759e0172639818719b20a5/mockup-3.2.6-py2.py3-none-any.whl (696kB)
     |████████████████████████████████| 706kB 19.1MB/s
Collecting persistent==4.7.0
  Using cached https://files.pythonhosted.org/packages/63/19/f95ae3d20840823754dacad879d0adf03bb290a2b763c6d9d85b020c0a2d/persistent-4.7.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/myuser/src/2021.ploneconf.org/api/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-yxxw3nyz/persistent/setup.py'"'"'; __file__='"'"'/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-yxxw3nyz/persistent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-yxxw3nyz/persistent/pip-egg-info
         cwd: /private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-yxxw3nyz/persistent/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /Users/myuser/src/2021.ploneconf.org/api/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-wheel-0evyincv/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-wheel-0evyincv/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-wheel-bpw3yja1
           cwd: /private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-wheel-0evyincv/cffi/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/myuser/src/2021.ploneconf.org/api/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/tmpvkqobmyz', '--quiet', 'cffi']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-yxxw3nyz/persistent/setup.py", line 88, in <module>
        setup(name='persistent',
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/myuser/src/2021.ploneconf.org/api/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/myuser/src/2021.ploneconf.org/api/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/tmpvkqobmyz', '--quiet', 'cffi']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by davisagli** [comment]
@tkimnguyen does it work to use the latest version of pip without this option? I think the option was there to avoid a performance problem that @mauritsvanrees helped fix in pip 22.0 (see https://github.com/pypa/pip/issues/10557)

**Comment by mauritsvanrees** [comment]
Correct. `--use-deprecated=legacy-resolver` only works with pip 20.something (not sure where it was introduced) or higher. And with pip 22 the option works, but is no longer needed for Plone.

But pip 22 only works with zc.buildout 3.0.0rc2 or higher, and that only works with `setuptools < 60` for now.

I fear packaging will always be complicated in some way...

**Comment by tkimnguyen** [comment]
Thanks @davisagli – it had gotten farther but got a different error which I will have to recreate. @mauritsvanrees 🤯😹 This repo seems to have pinned pip to 19.3.1 so how it had ever worked...

**Comment by ericof** [comment]
Let's close this and start working on the new site :-)

**Comment by tkimnguyen** [comment]
ok, I was going to use this as the basis for the new site. But it would also be nice to figure out the problem.
