### ISSUE TITLE
build-dev error on backend

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneconf.org#70]
`make install` as per the readme fails trying to build `persistent`. This is on the 2022 branch, macOS 12.5.1

```
Collecting BTrees
  Downloading BTrees-4.10.0.tar.gz (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.1/195.1 kB 4.7 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [154 lines of output]
      Collecting setuptools
        Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting persistent
        Downloading persistent-4.9.1.tar.gz (125 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 2.0 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting zope.interface
        Using cached zope.interface-5.4.0.tar.gz (249 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting cffi
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pycparser
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Building wheels for collected packages: persistent, cffi, zope.interface
        Building wheel for persistent (setup.py): started
        Building wheel for persistent (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [28 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
                _install_setup_requires(attrs)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
                return self.obtain(req, installer)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
                return installer(requirement)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 99, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 128, in _convert_metadata
                os.mkdir(destination_eggdir)
            FileExistsError: [Errno 17] File exists: '/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/.eggs/cffi-1.15.1-py3.8-macosx-10.14-arm64.egg'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for persistent
        Running setup.py clean for persistent
        error: subprocess-exited-with-error

        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [28 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
                _install_setup_requires(attrs)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
                return self.obtain(req, installer)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
                return installer(requirement)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 99, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 128, in _convert_metadata
                os.mkdir(destination_eggdir)
            FileExistsError: [Errno 17] File exists: '/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/.eggs/cffi-1.15.1-py3.8-macosx-10.14-arm64.egg'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for persistent
        Building wheel for cffi (setup.py): started
        Building wheel for cffi (setup.py): finished with status 'done'
        Created wheel for cffi: filename=cffi-1.15.1-cp38-cp38-macosx_10_14_arm64.whl size=260956 sha256=b0b8e53592f1c1ec99166782702eadb9bc3d85b6de3c2853b321f52d32ec7d46
        Stored in directory: /Users/kim/Library/Caches/pip/wheels/4f/6c/1c/87e97bb9c55afbf66881d37eed21c108b012c29105af6be450
        Building wheel for zope.interface (setup.py): started
        Building wheel for zope.interface (setup.py): finished with status 'done'
        Created wheel for zope.interface: filename=zope.interface-5.4.0-cp38-cp38-macosx_10_14_arm64.whl size=219797 sha256=4d31a0fbccec001e4faaed780ab8f30a59fde02bff19e3a8061d177f43127cff
        Stored in directory: /Users/kim/Library/Caches/pip/wheels/f6/d5/8a/522a527f3831d7baa52a67b0d6f45c5872aad25058e4a34b16
      Successfully built cffi zope.interface
      Failed to build persistent
      Installing collected packages: wheel, setuptools, pycparser, zope.interface, cffi, persistent
        Running setup.py install for persistent: started
        Running setup.py install for persistent: finished with status 'error'
        error: subprocess-exited-with-error

        × Running setup.py install for persistent did not run successfully.
        │ exit code: 1
        ╰─> [28 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/setup.py", line 88, in <module>
                setup(name='persistent',
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
                _install_setup_requires(attrs)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
                dist.fetch_build_eggs(dist.setup_requires)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
                resolved_dists = pkg_resources.working_set.resolve(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
                dist = best[req.key] = env.best_match(
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
                return self.obtain(req, installer)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
                return installer(requirement)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
                return fetch_build_egg(self, req)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
                wheel.install_as_egg(dist_location)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 99, in install_as_egg
                self._install_as_egg(destination_eggdir, zf)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
                self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
              File "/Users/kim/src/ploneconf.org/backend/lib/python3.8/site-packages/setuptools/wheel.py", line 128, in _convert_metadata
                os.mkdir(destination_eggdir)
            FileExistsError: [Errno 17] File exists: '/private/var/folders/0x/ws7_jwvj35x4wv_4d8g60hwm0000gn/T/pip-install-vn4sa7t4/persistent_31ea45814fe34dc983af6ba2d8dfb2a1/.eggs/cffi-1.15.1-py3.8-macosx-10.14-arm64.egg'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> persistent

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      WARNING: There was an error checking the latest version of pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
make[2]: *** [instance/etc/zope.ini] Error 1
make[1]: *** [install-backend] Error 2
make: *** [install] Error 2
```

**Comment by sneridagh** [comment]
all good here :( Python 3.8 as well:

```shell
cd backend
make build-dev
```

on an M1. Maybe some dependency missing? did you try to install `persistent` standalone with pip to see if the error is different there?
